### PR TITLE
feat | gets the monthly condo fee

### PR DESCRIPTION
**Pull request by paulovictorls**
The condo fee is an important factor when seeking for an apartment. Now the scraper gets it.

### CODE REVIEW

**Comment by GeovRodri** [comment]
Please, update README with the new field

**Comment by GeovRodri** [comment]
Thanks by contribute with project

**Comment by paulovictorls** [comment]
Just updated and added a possibility to insert a timer

**Comment by GeovRodri** [comment]
Ok, thanks. When you finish send a message to review PR

**Comment by paulovictorls** [comment]
You can review it now.

**Review by GeovRodri — APPROVED** [review]

**Comment by GeovRodri** [comment]
Thanks by contribute

**Pull request merged**
